INSERT INTO "uva" ("id", "name", "description", "active", "createdAt", "updatedAt") VALUES
('grape-cabernet-sauvignon', 'Cabernet Sauvignon', 'Uva tinta de grande estrutura, taninos marcantes e aromas de cassis, ameixa e especiarias.', true, NOW(), NOW()),
('grape-merlot', 'Merlot', 'Uva tinta macia e frutada, com notas de ameixa, frutas vermelhas e chocolate.', true, NOW(), NOW()),
('grape-malbec', 'Malbec', 'Uva tinta de cor intensa, corpo médio a encorpado e aromas de ameixa, violeta e frutas negras.', true, NOW(), NOW()),
('grape-tannat', 'Tannat', 'Uva tinta intensa e tânica, comum no Uruguai, com aromas de frutas negras e especiarias.', true, NOW(), NOW()),
('grape-pinot-noir', 'Pinot Noir', 'Uva tinta delicada e aromática, com notas de cereja, framboesa, terra e especiarias.', true, NOW(), NOW()),
('grape-syrah', 'Syrah', 'Uva tinta encorpada, com aromas de frutas negras, pimenta-preta e defumação.', true, NOW(), NOW()),
('grape-carmenere', 'Carménère', 'Uva tinta de textura sedosa, com notas de ameixa, pimentão maduro e ervas.', true, NOW(), NOW()),
('grape-cabernet-franc', 'Cabernet Franc', 'Uva tinta aromática, com taninos elegantes e notas de frutas vermelhas, ervas e pimenta.', true, NOW(), NOW()),
('grape-petit-verdot', 'Petit Verdot', 'Uva tinta de cor profunda, taninos firmes e aromas de violeta, frutas negras e especiarias.', true, NOW(), NOW()),
('grape-grenache', 'Grenache', 'Uva tinta de boa concentração alcoólica, com notas de frutas vermelhas, ervas e especiarias.', true, NOW(), NOW()),
('grape-mourvedre', 'Mourvèdre', 'Uva tinta estruturada, com aromas de frutas negras, ervas mediterrâneas, couro e especiarias.', true, NOW(), NOW()),
('grape-tempranillo', 'Tempranillo', 'Uva tinta espanhola de acidez equilibrada, com notas de cereja, ameixa, couro e baunilha.', true, NOW(), NOW()),
('grape-sangiovese', 'Sangiovese', 'Uva tinta italiana de boa acidez, com aromas de cereja, ervas, tomate seco e especiarias.', true, NOW(), NOW()),
('grape-nebbiolo', 'Nebbiolo', 'Uva tinta de alta acidez e taninos firmes, com notas de cereja, rosas, alcatrão e especiarias.', true, NOW(), NOW()),
('grape-barbera', 'Barbera', 'Uva tinta de acidez elevada e taninos moderados, com aromas de cereja, ameixa e ervas.', true, NOW(), NOW()),
('grape-touriga-nacional', 'Touriga Nacional', 'Uva tinta portuguesa concentrada e aromática, com notas de frutas negras, flores e especiarias.', true, NOW(), NOW()),
('grape-zinfandel', 'Zinfandel', 'Uva tinta frutada e intensa, com notas de frutas maduras, geleia, pimenta e especiarias.', true, NOW(), NOW()),
('grape-chardonnay', 'Chardonnay', 'Uva branca versátil, com aromas de maçã, pera e cítricos, podendo apresentar notas de manteiga e carvalho.', true, NOW(), NOW()),
('grape-sauvignon-blanc', 'Sauvignon Blanc', 'Uva branca fresca e aromática, com notas cítricas, maracujá, ervas e mineralidade.', true, NOW(), NOW()),
('grape-riesling', 'Riesling', 'Uva branca de alta acidez, com aromas de limão, maçã, flores e, com evolução, petróleo.', true, NOW(), NOW()),
('grape-pinot-grigio', 'Pinot Grigio', 'Uva branca leve e refrescante, com notas de pera, maçã, cítricos e flores brancas.', true, NOW(), NOW()),
('grape-chenin-blanc', 'Chenin Blanc', 'Uva branca de acidez elevada, com aromas de maçã, pera, mel e flores.', true, NOW(), NOW()),
('grape-gewurztraminer', 'Gewürztraminer', 'Uva branca muito aromática, com notas de lichia, rosas, especiarias e frutas tropicais.', true, NOW(), NOW()),
('grape-muscat', 'Moscato', 'Uva branca aromática e floral, com notas de uva fresca, pêssego, laranja e mel.', true, NOW(), NOW()),
('grape-viognier', 'Viognier', 'Uva branca encorpada e perfumada, com aromas de pêssego, damasco, flores e mel.', true, NOW(), NOW()),
('grape-albarino', 'Albariño', 'Uva branca fresca e mineral, com notas de limão, pêssego, flores e influência marítima.', true, NOW(), NOW()),
('grape-torrontes', 'Torrontés', 'Uva branca aromática argentina, com notas de flores, pêssego, cítricos e ervas.', true, NOW(), NOW()),
('grape-semillon', 'Sémillon', 'Uva branca de textura macia, com aromas de maçã, mel, ervas e frutas tropicais.', true, NOW(), NOW()),
('grape-trebbiano', 'Trebbiano', 'Uva branca de acidez refrescante, com notas cítricas, maçã verde e flores.', true, NOW(), NOW()),
('grape-garganega', 'Garganega', 'Uva branca italiana de boa acidez, com notas de limão, amêndoas, flores e mineralidade.', true, NOW(), NOW())
ON CONFLICT ("name") DO UPDATE SET "description" = EXCLUDED."description", "active" = true;
